// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace DatedComment
{
    internal sealed partial class Vsix
    {
        public const string Id = "DatedComment.af57fe93-7867-4bf3-a0dd-71398ea6f158";
        public const string Name = "Dated Comment";
        public const string Description = @"Insert a C# comment into the editor that includes the current user name, and current date and time.";
        public const string Language = "en-US";
        public const string Version = "1.1";
        public const string Author = "Tim WItort";
        public const string Tags = "";
    }
}
